from langchain.text_splitter import CharacterTextSplitter
from langchain_community.document_loaders import PyPDFLoader


text= """
Hello and welcome back to my blog😇. This post will be about a unique deep learning framework known as Generative Adversarial Networks (GANs), which I’ve found quite intriguing, not only because of how they work but also because of how they’re revolutionizing the way research problems in fluid dynamics, especially in reduced-order modeling and dynamical systems, are being approached.
Before GANs, most machine learning models were discriminative, meaning they were mainly used for classification or regression tasks. However I believe that GANs actually marked the beginning of the creative era in machine and deep learning. Yann LeCun, the Chief Scientist at Meta AI, once described GANs as “the most interesting idea in the last 10 years in Machine Learning” — and I really couldn’t agree more.


Yann LeCun on GANs
In as much as this framework has only been around since 2014, GANs have already made a solid mark in the fluid dynamics community. They’ve been used to create realistic flow field snapshots by learning the data distribution of actual fluid flows — which is a big deal. This means we can now produce fluid flow data without running full CFD simulations, which are often expensive. This is especially useful when you want to build an ML model but only have a limited amount of data to work with. GANs have also been used to generate new, plausible boundary condition profiles for simulations based on prior data — and that’s just one of many cool applications.

Now, if you’re not into fluid dynamics like I am 😎, GANs are still everywhere. They’ve been used to create hyper-realistic images of people that don’t actually exist haha. You can check out this website. Every time you refresh, a totally fake (but very realistic) human face pops up. Beyond that, GANs have been applied in generative design that enable you create cool 3d furniture for your home. Companies like Adobe are using GANs to build next-generation Photoshop tools, Google uses them for text generation, IBM uses them for data augmentation, and platforms like Snapchat and Tiktok have been using GANs to create image filters for quite a while now.

In this blog, I will be writing about the math behind the working of GANs, and I think the math is super important to learn about because it helps us understand why GANs work, not just that they work as well as move beyond the black-box thinking framework of deep learning models and gain the tools to improve or even invent new kinds of generative models. I would also advise you to read the original paper that introduced GANs to the world by Ian Goodfellow in 2014. Trust me, if you actually read this paper line by line (the source), there is a good chance you can easily eyeball any other paper written on GANs and have a good sense of what they are trying to accomplish with their own framework.


Generative Adversarial Nets Paper released in the June of 2014
To start with a high-level overview, Generative adversarial Networks are a type of deep learning framework composed of two parts: the generator and the discriminator. The generator usually samples noise- from a normal or Gaussian distribution — and produces some fake sample, let’s say a fake 2d temperature flow field. In this case, the generator can be seen as some type of art forger trying to create a fake sample of a 2D temperature flow field.

The discriminator on the other hand tries to guess if the flow field generated by the generator is fake or real. In this case, we can call the discriminator the judge.

If the generator succeeds in fooling the discriminator that the fake samples are real then it is doing a good job and the discriminator is doing a bad job. On the other hand, if the discriminator is good at spotting the fake samples produced by the generator, then it is doing an excellent job and the discriminator is doing a bad job and has more learning to do.

This back and forth usually called adversarial training, goes on for a while as each component gets better at its job and only stops when the discriminator cannot tell whether a sample generated by the discriminator is real or fake anymore. At this point it stops learning, the generator has now learned the probability distribution of the training data and we can say that the GAN training has converged.


Pictorial description of GANs
Since this blog is about the math of GANs, let’s take a deep dive into the world of math behind them🎯. In discriminative models like logistic regression, Support vector machines, and even some simple feed-forward neural networks used for classification, we learn the probability of a certain label given some input features. In generative models, we learn two things, the probability of a certain label as well as the probability of the input features given the learned label. This is known as the joint probability distribution of the input features and their corresponding labels. In case what you just read above does not sound intuitive here is an even better explanation using animals. A discriminative model learns to say: “Given this image with certain features, is it a cat or a dog?” meanwhile a generative model learns to say: “I’ve learned what a cat looks like. Now, I can create a new, realistic image of a cat — even if that cat doesn’t exist in real life”. With this type of joint probability, the generator learns the probability distribution of the training data and is able to produce hyperrealistic images of cats that do not exist in this case. Mathematically speaking the image below explains what this means in probabilistic terms .


Discriminative and Generative Models in terms of Probabilities
The image below shows a high-level view of what a GAN actually looks like. The generator could be a simple feedforward neural network, a transposed convolutional neural network, or a decoder. The discriminator could also be a simple feedforward neural network, a convolutional neural network, or even an autoencoder. The choice of architecture really depends on the use case of the GAN you are trying to build, but in each case, both parts of the GAN play their respective roles diligently.


Notation Summary for GAN Architecture
z represents noise sampled from a gaussian or normal distribution
G represents the generator that generates fake images from the sampled noise
G(z) represents the noise generated
D represents the discriminator
X is the domain of the real data samples
θg represents the weights and biases of the generator updated during gradient ascent.
θd represents the weights and biases of the discriminator updated during gradient descent.
If you think about it , the way GANs work can actually be modelled as a minimax game where;

The Generator tries to minimize it’s chances of getting caught generating fake data samples while the discriminator tries to maximize it’s chances of spotting the fake data samples produced by the generator.

In mathematical terms , we can say that generator tries to minimize and the discriminator tries to maximize the value function given as V which is our loss function.


minimax game of GANs
Above, you can see two equations: the minimax formulation of the value function and the value function itself. I’ll explain the second equation in a way that makes it easy to understand.
Looking at the second equation, you’ll notice that it closely resembles the binary cross-entropy loss function, which is given by:


Binary cross entropy loss
Y represents the true label for the i-th sample
Y-hat represents the prediction from the discriminator
n is the number of samples in the dataset or batch
The value function is derived from the binary cross-entropy loss. The binary cross-entropy objective function provides a measure of how far we are from achieving our goal of correctly classifying real and fake samples. To undertand how the BCE loss function works , take a look at the image below .


BCE loss function.
Only left part of the BCE loss indicated in green only matters when the ground truth of the data sample is real or 1. Meanwhile only the right part of the loss function matters when the ground truth of the data sample is fake or 0. Looking at the image below when y= 1 , the loss function is close to 0 when the prediction is close to 1 and infinity when the prediction is close to 0 .When y=0 , the loss function is close to 0 when the prediction is close to 0 and infinity when the prediction is close to 1.


Prediction and Loss for BCE loss function
Adding both parts of the binary cross-entropy loss — the case when the ground truth is 1 (real) and when it is 0 (fake) — gives us the value function used in Generative Adversarial Networks (GANs). Since this value function must be computed over many data points, we use expectations (denoted by E) to represent the average loss over the data distribution.

In the context of GANs, the discriminator aims to maximize this loss function by correctly classifying real as real and fake as fake and the generator aims to minimize it by fooling the discriminator into thinking the fake data is real.


Minimax of the Value function V(D,G)
It is also important to note that the generator has no effect on D(x) which are the real data samples as it does not generate real data samples . All real data samples are fed into the discriminator separately during training .

Training Generative Adversarial Networks
The image below is from the original paper that introduced GANs back in 2014. It shows the algorithm used to train GANs. I’m going to break it down in a way that makes intuitive sense🙃, but first, take a moment to read through it — and if you haven’t already, make sure to check out the full paper too!


Algorithm for training GANs from original GAN paper in 2014
Firstly, some samples of noise were generated from a uniform distribution and fed into the generator to produce fake data samples. . The generator was then disconnected, and the fake images were fed into the discriminator alongside real images sampled from the real data distribution. The weights and biases of the discriminator are then updated using gradient ascent by finding the global maximum.
Secondly, the discriminator was disconnected, and the generator was trained by generating fake images and passing them into the discriminator. The generator’s parameters (weights and biases) were then updated using gradient descent. Both the discriminator and the generator were updated once per training cycle.

Pictorial description of gradient ascent and descent loss landscape
In reality the function the neural net of the discriminator and the generator fit to the data is way more complex than the convex and concave functions you see in the image above. The images represents the simplest forms of gradient descent and ascent.

Architecture of Generator and Discriminator
The generator was a simple feedforward neural network with just one hidden layer, a ReLU activation function, and a tanh activation function at the output layer to squash the outputs to values between -1 and 1, representing pixel intensity values for the MNIST dataset.
The discriminator was a simple feedforward neural network with just one hidden layer . The hidden layer used leaky RELU activation functions while the output layer had just one neuron with a sigmoid activation to squash the outputs to probabilities of being fake (0) or real (1) .
Maximization and Minimization of the value function with Math.
For a detached or fixed generator after generating fake images, the goal of the discriminator is to maximize the value function which can be written mathematically as:


Maximization of the value function with Gradient Ascent
The Discriminator maximizes the value function when D(x) is given as Pd(x)/[Pd(x) +Pg(x)] where Pd(x) is the probability distribution of the real data samples and Pg(x) is the probability distribution of the fake data samples. The generator on the other hand seeks to minimize this maximized function. To minimize the maximized function, we need the probability distribution of the real data to be the same as the probability distribution of the generated data sample. Since we want to make them equal we need a measure of how far apart these two distributions are . To measure that we use the JS (Jensen–Shannon) divergence which is calculated using the KL (Kullback-Leibler) divergence👌 .


Minimization of the value function by the generator .
The Jensen-Shannon divergence looks very similar to the maximized value function that we want to minimize using the generator 👌. To minimize the value function , the probability distribution of the real data samples must be equal to that of the generated data samples . When we achieve that the value function becomes -2In2. At this point the discriminator can no longer decipher the real(1) from the fake(0) data samples and outputs 0.5 for all inputs .


When we get to the point where the discriminator get’s stuck and cannot decide anymore , we stop training. The training of GANs is explained visually in the image below gotten from the original paper.


Generator -green , Discriminator -blue , Training data distribution- Black dotted line. GAN paper 2014
At the beginning of training, neither the discriminator nor the generator has any real idea of what they’re doing. The discriminator’s weights and biases are updated in (b), while the generator’s parameters are frozen. Then in (c), the generator’s weights and biases are updated while the discriminator’s parameters are frozen. This loop keeps repeating during adversarial training, and over time, the generator’s data distribution matches that of the training data in (d), meanwhile the discriminator becomes a straight blue line that outputs 0.5 for all data samples. At this point, the generator has learned the data distribution of the training set and can generate data samples that look similar to the real ones.

Thanks for reading up to this point☺️! I hope the math behind how GANs work has been helpful and that you’re now better prepared to start building your own GAN networks. To deepen your understanding, I recommend exploring more about KL divergence, JS divergence, and the stability challenges commonly encountered during GAN training.

You might also want to look into advanced topics like Wasserstein GANs, Boundary Equilibrium GANs, Lipschitz continuity enforcement, batch normalization techniques in GANs training, spectral normalization in GANs, and deep convolutional GANs (DCGANs). These will give you a broader perspective and help you train more stable and effective GAN models. Also do well to check out this cool podcast with the Inventor of this deep learning architecture and Lex Fridman.


Podcast — Ian Goodfellow and Lex Fridman
References
The Math of GANs explained YouTube
Overview of GAN Structure-Google for developers
A Gentle Introduction to Generative Adversarial Nets — ML Mastery
Understanding GANs- YouTube

"""

loader = PyPDFLoader("syllabus.pdf")

docs = loader.load()

splitter = CharacterTextSplitter(
    chunk_size =  500,
    chunk_overlap = 0,
    separator =''
)

result = splitter.split_documents(docs)

print(result[0].page_content)
